#!/bin/sh
set -e

case "$1" in
    remove)
        # Remove logs
        rm -rf /var/log/oauthd
        
        # remove **only** empty data dir
        # rmdir -p --ignore-fail-on-non-empty /var/lib/oauthd
    ;;

    purge)
        # Remove service
        update-rc.d oauthd remove >/dev/null || true
    
        # Remove logs and data
        # rm -rf /var/log/oauthd /var/lib/oauthd

        # Remove user/group
        deluser oauth || true
        delgroup oauth || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
