#!/bin/sh
set -e

case "$1" in
    configure)
    [ -f /etc/default/greenpas-oauth ] && . /etc/default/greenpas-oauth
    [ -z "$OAUTH_USER" ] && OAUTH_USER="oauth"
    [ -z "$OAUTH_GROUP" ] && OAUTH_GROUP="oauth"
    if ! getent group "$OAUTH_GROUP" > /dev/null 2>&1 ; then
        addgroup --system "$OAUTH_GROUP" --quiet
    fi
    if ! id $OAUTH_USER > /dev/null 2>&1 ; then
        adduser --system --home /usr/share/greenpas-oauth --no-create-home \
        --ingroup "$OAUTH_GROUP" --disabled-password --shell /bin/false \
        "$OAUTH_USER"
    fi

    # Set user permissions on /var/log/greenpas-oauth and /var/lib/greenpas-oauth
    mkdir -p /var/log/greenpas-oauth /var/lib/greenpas-oauth
    chown -R $OAUTH_USER:$OAUTH_GROUP /var/log/greenpas-oauth /var/lib/greenpas-oauth
    chmod 755 /var/log/greenpas-oauth /var/lib/greenpas-oauth

    # configuration files should not be modifiable by greenpas-oauth user, as this can be a security issue
    chown -Rh root:root /etc/greenpas-oauth/*
    chmod 755 /etc/greenpas-oauth
    chmod 644 /etc/greenpas-oauth/*
    ;;
esac

if [ -x "/etc/init.d/greenpas-oauth" ]; then
    update-rc.d greenpas-oauth defaults 95 10 >/dev/null
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        invoke-rc.d greenpas-oauth start || true
    else
        /etc/init.d/greenpas-oauth start || true
    fi
fi
