#!/bin/sh
set -e

if [ -x "/etc/init.d/oauthd" ]; then
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        invoke-rc.d oauthd stop || true
    else
        /etc/init.d/oauthd stop || true
    fi
fi
