#!/bin/sh
set -e

if [ -x "/etc/init.d/greenpas-oauth" ]; then
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        invoke-rc.d greenpas-oauth stop || true
    else
        /etc/init.d/greenpas-oauth stop || true
    fi
fi
